nextflow.enable.dsl = 2


/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Nextflow Process: SAMPLESHEET VALIDATION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Description:
# This process runs a Python script to validate a samplesheet file.
# The validation script ensures the samplesheet is properly formatted
#
# Input:
# - path(python): Path to the Python script responsible for performing the validation.
# - path(samplesheet): Path to the samplesheet file that needs validation.
#
# Output:
# - Tuple: val(meta), path("*{3prime,5prime,trimmed,val}*.fq.gz")
#   - Trimmed FASTQ files with various suffixes indicating trimming types.

# - Tuple: val(meta), path("*report.txt")
#   - Report file generated by Trim Galore, detailing the trimming process.

# - Tuple: val(meta), path("*.html")
#   - HTML report file generated by FastQC, summarizing the quality of the trimmed reads.

# - Tuple: val(meta), path("*.zip")
#   - Compressed file of the output, if applicable.

# - Path: versions.yml
#   - YAML file containing the versions of Trim Galore and Cutadapt used in the process.
#
# Author: Annika, Maike, Tabea, Weronika
# Date: 09.10.2024
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

process SAMPLESHEET_VALIDATION {

    input:
    path python
    path samplesheet

    output:
    path validation

    script:
    """
    python $python $samplesheet > "${params.outdir}/samplesheet_validation/validation.txt"

    """
}

