/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Simple RNA Sequencing Pipeline
# Author: Weronika Jaśkowiak, Maike Nägele, Tabea Attig, Annika Maier
# Date: 11.10.2024
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
nextflow.enable.dsl = 2

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Nextflow Process: SAMPLESHEET VALIDATION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Description:
# The SAMPLESHEET_VALIDATION process checks the validity of a given samplesheet
# using a Python script. The VALIDATION_SUCCESS process checks whether the
# validation passed by analyzing the output of the validation.
#
# SAMPLESHEET_VALIDATION:
# Input:
# - path(python): Path to the Python script that performs the validation.
# - path(samplesheet): Path to the samplesheet file that needs to be validated.
#
# Output:
# - path "validation.txt": Text file containing the results of the samplesheet validation.
#
# VALIDATION_SUCCESS:
# Input:
# - path(validation_file): Path to the validation.txt file generated by the
#   SAMPLESHEET_VALIDATION process.
#
# Output:
# - stdout: Boolean result indicating whether the samplesheet validation was successful
#   ("true" if successful, "false" if failed).
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/


process SAMPLESHEET_VALIDATION {

    debug true

    input:
    path python
    path samplesheet

    output:
    //path "validation.txt", emit: validation
    // val text, emit: validation
    script:
    """
    python $python -file $samplesheet

    echo "content of validation file"
    echo cat "validation.txt"

    if grep -q "failed" "validation.txt"; then
        echo "failed"
        exit 1
    else
        echo "success"    
    fi    

    #filecontent=\$(cat "validation.txt")
    #echo "file content"
    #echo "\${filecontent}""
    """
}

// process VALIDATION_SUCCESS {

//     debug true 

//     input:
//     path validation_file

//     output:
//     val output, emit: output

//     script:
//     """
//     filecontent=\$(cat {$validation_file})
//     echo "file content"
//     echo "\${filecontent}"
//     """
// }